name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  macos_build:
    name: MacOS (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["macos-13", "macos-14"]
    runs-on: ${{ matrix.OS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: sbt

      - uses: sbt/setup-sbt@v1

      - name: Build the binary
        run: sbt buildBinary

  linux_build:
    name: Linux (${{ matrix.OS }})
    strategy:
      fail-fast: true
      matrix:
        OS: ["ubuntu-22.04", "ubuntu-22.04-arm"]
    runs-on: ${{ matrix.OS }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '21'
        cache: 'sbt'

    - uses: sbt/setup-sbt@v1

    - name: Build the binary
      run: sbt buildBinary


  windows_build:
    name: Windows
    strategy:
      fail-fast: false
    runs-on: windows-2022
    env:
      LLVM_BIN: 'C:\Program Files\LLVM\bin'
      LLVM_VERSION: "17.0.6"
    steps:
      # This step is important to make sure scalafmt 
      # checks don't fail
      - name: Setup git config
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' 
          java-version: '21'
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1

      # See https://github.com/scala-native/scala-native/blob/master/.github/actions/windows-setup-env/action.yml#L14 SN_RELE
      # for details
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 4GB
          maximum-size: 16GB

      - name: Install clang and SBT
        shell: pwsh
        run: |
          choco install llvm --version="$Env:LLVM_VERSION" --allow-downgrade
          choco install sbt --version=1.10.7
          clang --version

      - name: Build binary (windows)
        run: sbt buildBinary
        shell: cmd


  mergify-build-checkpoint:
    runs-on: ubuntu-latest
    needs: [linux_build, windows_build, macos_build]
    steps:
      - name: I only exist to please Mergify :(
        run: echo "It's a sad existence but necessary"
